		<script src="js/vendor/jquery.js"></script>
		<script src="js/vendor/what-input.js"></script>
		<script src="js/vendor/foundation.js"></script>
		<script src="js/vendor/swiper.min.js"></script>
		<script src="js/vendor/jquery.mousewheel-3.0.6.pack.js"></script>
		<script src="js/vendor/fancybox/jquery.fancybox.js?v=2.1.5"></script>
		<script src="js/vendor/fancybox/helpers/jquery.fancybox-buttons.js?v=1.0.5"></script>
		<script src="js/vendor/fancybox/helpers/jquery.fancybox-thumbs.js?v=1.0.7"></script>
		<script src="js/vendor/fancybox/helpers/jquery.fancybox-media.js?v=1.0.6"></script>
		<script src="js/app.js"></script>